"""empty message

Revision ID: 37f6816beff3
Revises: 
Create Date: 2020-03-25 12:25:48.363430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37f6816beff3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email_id', sa.String(length=254), nullable=False),
    sa.Column('name', sa.String(length=70), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=11), nullable=False),
    sa.Column('logged_in', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('email_id')
    )
    op.create_table('vehicle',
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.Column('license_plate', sa.String(length=11), nullable=False),
    sa.Column('driver', sa.String(length=70), nullable=False),
    sa.Column('model', sa.String(length=40), nullable=False),
    sa.Column('type', sa.String(length=9), nullable=False),
    sa.Column('brakes_health', sa.Float(precision=3), nullable=True),
    sa.Column('engine_health', sa.Float(precision=3), nullable=True),
    sa.Column('fuel_health', sa.Float(precision=3), nullable=True),
    sa.Column('tyres_health', sa.Float(precision=3), nullable=True),
    sa.Column('overall_health', sa.Float(precision=3), nullable=True),
    sa.PrimaryKeyConstraint('vin'),
    sa.UniqueConstraint('license_plate')
    )
    op.create_table('firebase_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=256), nullable=True),
    sa.Column('user_email', sa.String(length=254), nullable=True),
    sa.ForeignKeyConstraint(['user_email'], ['user.email_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('firebase_token')
    op.drop_table('vehicle')
    op.drop_table('user')
    # ### end Alembic commands ###
