"""empty message

Revision ID: 50c9874381fb
Revises: 
Create Date: 2020-02-20 14:01:17.140334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50c9874381fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email_id', sa.String(length=254), nullable=False),
    sa.Column('name', sa.String(length=70), nullable=True),
    sa.Column('password_hash', sa.String(length=16), nullable=True),
    sa.Column('role', sa.String(length=11), nullable=True),
    sa.PrimaryKeyConstraint('email_id')
    )
    op.create_table('vehicle',
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.Column('license_plate', sa.String(length=11), nullable=False),
    sa.Column('driver', sa.String(length=70), nullable=False),
    sa.Column('model', sa.String(length=40), nullable=False),
    sa.Column('type', sa.String(length=9), nullable=False),
    sa.Column('brake_health', sa.Float(precision=3), nullable=True),
    sa.Column('engine_health', sa.Float(precision=3), nullable=True),
    sa.Column('fuel_health', sa.Float(precision=3), nullable=True),
    sa.Column('tyre_health', sa.Float(precision=3), nullable=True),
    sa.Column('system_health', sa.Float(precision=3), nullable=True),
    sa.PrimaryKeyConstraint('vin'),
    sa.UniqueConstraint('license_plate')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle')
    op.drop_table('user')
    # ### end Alembic commands ###
