"""empty message

Revision ID: 892e9f26b779
Revises: cd565534c626
Create Date: 2020-02-20 18:44:06.233704

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '892e9f26b779'
down_revision = 'cd565534c626'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=80), nullable=False))
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', mysql.VARCHAR(length=80), nullable=False))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
