"""empty message

Revision ID: cd565534c626
Revises: 5d9e29c73dad
Create Date: 2020-02-20 16:11:19.096962

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd565534c626'
down_revision = '5d9e29c73dad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('brakes_health', sa.Float(precision=3), nullable=True))
    op.add_column('vehicle', sa.Column('overall_health', sa.Float(precision=3), nullable=True))
    op.add_column('vehicle', sa.Column('tyres_health', sa.Float(precision=3), nullable=True))
    op.drop_column('vehicle', 'system_health')
    op.drop_column('vehicle', 'brake_health')
    op.drop_column('vehicle', 'tyre_health')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('tyre_health', mysql.FLOAT(), nullable=True))
    op.add_column('vehicle', sa.Column('brake_health', mysql.FLOAT(), nullable=True))
    op.add_column('vehicle', sa.Column('system_health', mysql.FLOAT(), nullable=True))
    op.drop_column('vehicle', 'tyres_health')
    op.drop_column('vehicle', 'overall_health')
    op.drop_column('vehicle', 'brakes_health')
    # ### end Alembic commands ###
